### ISSUE TITLE
[Gold Custom]: Health Gateway

### ISSUE THREAD

**Issue by ninosamson** [bcgov/sso-keycloak#181]
### Product Owner Contact Details

nino.samson@gov.bc.ca

### Technical Owner Contact Details

stephen.s.laws@gov.bc.ca

### Silver custom realm name

ff09qn3f

### New realm name

Health Gateway Gold 

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
Provisioned.
