### ISSUE TITLE
[Gold Custom]: BCParks

### ISSUE THREAD

**Issue by JLWade** [bcgov/sso-keycloak#182]
### Product Owner Contact Details

jessica.wade@gov.bc.ca

### Technical Owner Contact Details

mark@digitalspace.ca

### Secondary Technical Owner Contact Details

Wilson.1.Wong@gov.bc.ca

### Silver custom realm name

g7v0xlf4

### New realm name

BCParks_ServiceTransformation

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
Sent email with details
