### ISSUE TITLE
[Gold Custom]: WorkBC ES

### ISSUE THREAD

**Issue by rafasdc** [bcgov/sso-keycloak#185]
### Product Owner Contact Details

jeff.dorion@gov.bc.ca

### Technical Owner Contact Details

rafael.solorzano@gov.bc.ca

### Secondary Technical Owner Contact Details

leo.lou@gov.bc.ca

### Silver custom realm name

3nwwef1

### New realm name

workbces

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
