### ISSUE TITLE
[Gold Custom]: Advanced Ed

### ISSUE THREAD

**Issue by abschwenker** [bcgov/sso-keycloak#190]
### Product Owner Contact Details

kailyn.sherk@gov.bc.ca

### Technical Owner Contact Details

andrew.schwenker@gov.bc.ca

### Secondary Technical Owner Contact Details

andrew.schwenker@gov.bc.ca

### Silver custom realm name

jxoe2o46

### New realm name

AESTSIMS

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
Provisioned
