### ISSUE TITLE
[Gold Custom]: SDPR/MCFD - Social Sector

### ISSUE THREAD

**Issue by ll911** [bcgov/sso-keycloak#192]
### Product Owner Contact Details

leo.lou@gov.bc.ca

### Technical Owner Contact Details

fred.wen@gov.bc.ca

### Secondary Technical Owner Contact Details

fred.wen@gov.bc.ca

### Silver custom realm name

gde0rjxl, secimg

### New realm name

social

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by f-w** [comment]
Can new realm name in gold cluster be more meaningful, something like socialSector or ss for short?

**Comment by zsamji** [comment]
> Can new realm name in gold cluster be more meaningful, something like socialSector or ss for short?

@f-w  and @ll911  can you please suggest the new name?

**Comment by ll911** [comment]
updated to `social`

**Comment by zsamji** [comment]
provisioned.
