### ISSUE TITLE
[Gold Custom]:  BC Registries and Online Services

### ISSUE THREAD

**Issue by pwei1018** [bcgov/sso-keycloak#193]
### Product Owner Contact Details

john.a.m.lane@gov.bc.ca

### Technical Owner Contact Details

patrick.wei@gov.bc.ca

### Secondary Technical Owner Contact Details

andriy.bolyachevets@gov.bc.ca

### Silver custom realm name

fcf0kpqr

### New realm name

bcregistry

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
