### ISSUE TITLE
[Gold Custom]: MOTI

### ISSUE THREAD

**Issue by bcgov-brwang** [bcgov/sso-keycloak#194]
### Product Owner Contact Details

bruce.wang@gov.bc.ca

### Technical Owner Contact Details

bruce.wang@gov.bc.ca

### Silver custom realm name

kmas316h

### New realm name

moti-custom

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
