### ISSUE TITLE
[Gold Custom]: CSST

### ISSUE THREAD

**Issue by TimCsaky** [bcgov/sso-keycloak#195]
### Product Owner Contact Details

sharolyn.hurley@gov.bc.ca

### Technical Owner Contact Details

tim.csaky@gov.bc.ca

### Secondary Technical Owner Contact Details

jeremy.ho@gov.bc.ca

### Silver custom realm name

jbd6rnxw

### New realm name

csst

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
@TimCsaky remind me again what does ccst stand for?

**Comment by TimCsaky** [comment]
Hi @zsamji 
I suggested 'CSST' (not CCST) but we could choose something else if it's too much like CSS (Common Single Sign-on)
we use acronym CSST for 'Common Services Showcase Team'. 
other choices could be: comsvc or comsvcauth

**Comment by zsamji** [comment]
provisioned as comsvcauth
