### ISSUE TITLE
[Gold Custom]: digitaltrust-nrm

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/sso-keycloak#196]
### Product Owner Contact Details

kyle.1.robinson@gov.bc.ca

### Technical Owner Contact Details

lucas.oneil@gov.bc.ca

### Secondary Technical Owner Contact Details

jason@usingtechnolo.gy

### Silver custom realm name

digitaltrust

### New realm name

digitaltrust-nrm

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
Provisioned
