### ISSUE TITLE
[Gold Custom]: FOI Team

### ISSUE THREAD

**Issue by lmullane** [bcgov/sso-keycloak#197]
### Product Owner Contact Details

Loren.Mullane@gov.bc.ca

### Technical Owner Contact Details

Abin.Antony@gov.bc.ca

### Secondary Technical Owner Contact Details

Adam.Coard@gov.bc.ca

### Silver custom realm name

5k8dbl4h

### New realm name

FOI-mod

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
