### ISSUE TITLE
[Gold Custom]: APS

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/sso-keycloak#200]
### Product Owner Contact Details

Johnathan.Brammall@gov.bc.ca

### Technical Owner Contact Details

aidan.cope@gmail.com

### Secondary Technical Owner Contact Details

Justin.Tendeck@gov.bc.ca

### Silver custom realm name

xtmke7ky

### New realm name

apigw

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
