### ISSUE TITLE
[Gold Custom]: Service BC

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/sso-keycloak#201]
### Product Owner Contact Details

Leslie.Rewega@gov.bc.ca

### Technical Owner Contact Details

Jose.Kudiyirippil@gov.bc.ca

### Secondary Technical Owner Contact Details

Walter.Moar@gov.bc.ca

### Silver custom realm name

vtkayq4c

### New realm name

servicebc

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
Provisioned
