### ISSUE TITLE
[Gold Custom]: CHEFS

### ISSUE THREAD

**Issue by jasonchung1871** [bcgov/sso-keycloak#202]
### Product Owner Contact Details

andrew.brennan@gov.bc.ca

### Technical Owner Contact Details

jason.chung@gov.bc.ca

### Silver custom realm name

cp1qly2d

### New realm name

CHEFS

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
