### ISSUE TITLE
[Gold Custom]:Digitaltrust-citz

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/sso-keycloak#203]
### Product Owner Contact Details

charles.macpherson@gov.bc.ca

### Technical Owner Contact Details

wade@neoterictech.ca

### Secondary Technical Owner Contact Details

clecio.varjao@gov.bc.ca

### Silver custom realm name

gzyg46lx

### New realm name

ditpbcdts

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
@WadeBarnes curious what does ditpbcdts stand for - can we use something a little more human wordy?

**Comment by WadeBarnes** [comment]
lol.  It stands for Digital Identity and Trust Program BC Digital Trust Services.  @krobinsonca already stole `digitaltrust`.  @zsamji, would `bcdts` (BC Digital Trust Services) be ok with you?

**Comment by krobinsonca** [comment]
LOL, sorry.

Question though, should we use the same KC?

Kyle Robinson, Consultant
Senior Strategic Advisor, Digital Trust Ecosystems
Mines Digital Trust
***@***.******@***.***>
Phone: 250-661-3611<tel:+12506613611>

**Comment by WadeBarnes** [comment]
> LOL, sorry. Question though, should we use the same KC?

That might make sense, since we are both using VCs and the projects are closely related.

**Comment by zsamji** [comment]
@WadeBarnes  can we call yours digitaltrust-citz and @krobinsonca call yours digitaltrust-nrm?

**Comment by WadeBarnes** [comment]
> @WadeBarnes can we call yours digitaltrust-citz and @krobinsonca call yours digitaltrust-nrm?

Works for me.

**Comment by krobinsonca** [comment]
Yes, that works for me.

Kyle Robinson, Consultant
Senior Strategic Advisor, Digital Trust Ecosystems
Mines Digital Trust
***@***.******@***.***>
Phone: 250-661-3611<tel:+12506613611>

**Comment by zsamji** [comment]
provisioned
