### ISSUE TITLE
[Gold Custom]:  Zeva team

### ISSUE THREAD

**Issue by kuanfandevops** [bcgov/sso-keycloak#204]
### Product Owner Contact Details

James.Donald@gov.bc.ca

### Technical Owner Contact Details

Kuan.Fan@gov.bc.ca

### Secondary Technical Owner Contact Details

alex@bigthink.io

### Silver custom realm name

rzh2zkjq

### New realm name

zelda

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
