### ISSUE TITLE
[Gold Custom]: Prime

### ISSUE THREAD

**Issue by nick-mailhot** [bcgov/sso-keycloak#207]
### Product Owner Contact Details

leanne.warren@gov.bc.ca

### Technical Owner Contact Details

nelson.lah@gov.bc.ca

### Secondary Technical Owner Contact Details

nick.1.mailhot@gov.bc.ca

### Silver custom realm name

v4mbqqas

### New realm name

PRIME

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
to be migrated
