### ISSUE TITLE
[Gold Custom]: HCAP

### ISSUE THREAD

**Issue by awjdennison** [bcgov/sso-keycloak#215]
### Product Owner Contact Details

Paul.McDonnell@gov.bc.ca

### Technical Owner Contact Details

Will.Sonnex@ca.ey.com

### Secondary Technical Owner Contact Details

Rachit.Khare@ca.ey.com

### Silver custom realm name

4qjrpzzl

### New realm name

hcap

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
