### ISSUE TITLE
[Gold Custom]: Public Cloud Accelerator Service

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/sso-keycloak#218]
### Product Owner Contact Details

julian.subda@gov.bc.ca

### Technical Owner Contact Details

max.wardle@gov.bc.ca

### Silver custom realm name

umafubc9 & tml5tvs

### New realm name

public_cloud

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by ActionAnalytics** [comment]
7.6 is the version in Gold (we are happy about that)

**Comment by zsamji** [comment]
discussed with @ActionAnalytics changing name to public_cloud

**Comment by zsamji** [comment]
provisioned
