### ISSUE TITLE
[Gold Custom]:eao-epic

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/sso-keycloak#220]
### Product Owner Contact Details

sid.tobias@gov.bc.ca

### Technical Owner Contact Details

geoff.l.mcdonald@gov.bc.ca

### Secondary Technical Owner Contact Details

carly.greenehill@gov.bc.ca

### Silver custom realm name

eagle

### New realm name

eao-epic

### Gold environment needed

- [X] Dev
- [x] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
