### ISSUE TITLE
[Gold Custom]: Wildfire

### ISSUE THREAD

**Issue by WillRobins32** [bcgov/sso-keycloak#232]
### Product Owner Contact Details

Cary.Nukina@gov.bc.ca

### Technical Owner Contact Details

tbell@selkirksystems.com

### Secondary Technical Owner Contact Details

Will.Robins@gov.bc.ca

### Silver custom realm name

gsr30myh

### New realm name

Wildfire

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
provisioned
