### ISSUE TITLE
WIKI Feedback

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/sso-keycloak#233]
I started with the CSS App and went to the "Pathfinder Knowledge Base", then went down the list of links in the Wiki TOC. Did not review Wiki pages that were not linked in the TOC (assumed they are "internal")

CSS FAQ

- "Requires role management, session management, scopes or changes in token times" -- role management is a feature now, so maybe remove that reference

Home Page

- Is Github in or out? Conflicting messages on this page
- Talks about standard realm and says custom realm is not allowed -- probably need to mention that custom realms exist per ministry
- Probably a good place to mention that we are now on Gold and link to service agreement

SSO Onboarding

- No comment

Using Your SSO Client

- Links out to CSS FAQ and a discussions page. Now I'm starting to get overwhelmed with number of locations for docs
- "Environments and Accounts" mentions "Silver" and "Gold" for the first time, but I have not heard of these before in the Knowledge Base

What is Keycloak @ BC Government?

- This page probably needs an update if Github is back in
- This page links to "useful references" which mentions Azure IDIR for the first time. I would have thought that would have been on the list of IDPs or mentioned in the list that describes the kc-idp-hint options

BC Service Card Integration

- References "realm per sector" but talks about it as a possible future strategy -- needs an update

Identity Provider Attribute Mapping

- Confusing but really worth it. Please keep the "developer" version up to date (it's really confusing when that page doesn't match the visual)

Handling Authorization

- Links to another page on the Wiki. Just make one page and fix the table of contents please.

Gold Migration Q&A

- Jumped me to a discussion page which was a bit jarring (I left the Wiki)

**Comment by zsamji** [comment]
set up meeting for Dec 5
