### ISSUE TITLE
[Gold Custom]: Please provision a custom realm for migration of tz0e228w in Silver.

### ISSUE THREAD

**Issue by pwpv** [bcgov/sso-keycloak#285]
### Product Owner Contact Details

Patricia.M.White@gov.bc.ca

### Technical Owner Contact Details

Wade.Barnes@gov.bc.ca

### Secondary Technical Owner Contact Details

Ryan.Loiselle@gov.bc.ca

### Silver custom realm name

tz0e228w

### New realm name

court-services-jag

### Gold environment needed

- [X] Dev
- [X] Test
- [X] Prod

### Code of Conduct

- [X] I agree to follow Pathfinder SSO's Gold Custom Realm Community Ways of Working

**Comment by zsamji** [comment]
in progress

**Comment by zsamji** [comment]
provisioned
